#!/bin/bash

set +e  # Don't exit immediately if a command exits with a non-zero status

script=$(basename "$0")

find ../day_1 ../day_2 -name top.v  \
| sed "s/\/top\.v//" \
| while read dir
  do
    case "$dir" in
    *omdazz*)          board="omdazz"    ;;
    *zeowaa*)          board="zeowaa"    ;;
    *de10_lite*)       board="de10_lite" ;;
    *basys3*|*nexys4*) continue          ;;

    *)
      printf "$script: unrecognized directory '%s'" "$dir" 1>&2
      exit 1
    esac

    echo $dir 1>&2

    if    ! rm -rf "$dir/run" \
       || ! mkdir  "$dir/run" \
       || ! cp -r all_intel_fpga_boards/* $board/* "$dir/run"
    then
      printf "$script: cannot copy into '%s'" "$dir/run" 1>&2
      exit 1
    fi
  done

exit 0
